[2025-06-19T12:06:17.993+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T09:00:00+00:00 [queued]>
[2025-06-19T12:06:18.010+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T09:00:00+00:00 [queued]>
[2025-06-19T12:06:18.011+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T12:06:18.032+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 09:00:00+00:00
[2025-06-19T12:06:18.046+0000] {standard_task_runner.py:60} INFO - Started process 1596 to run task
[2025-06-19T12:06:18.058+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T09:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmpxywbmypb']
[2025-06-19T12:06:18.062+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask validate_data
[2025-06-19T12:06:18.149+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T09:00:00+00:00 [running]> on host 77bf71b7bc3a
[2025-06-19T12:06:18.359+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T09:00:00+00:00'
[2025-06-19T12:06:18.362+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T12:06:18.382+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T090000, start_date=20250619T120617, end_date=20250619T120618
[2025-06-19T12:06:18.449+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T12:06:18.529+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T12:19:09.496+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T09:00:00+00:00 [queued]>
[2025-06-19T12:19:09.560+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T09:00:00+00:00 [queued]>
[2025-06-19T12:19:09.567+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T12:19:09.664+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 09:00:00+00:00
[2025-06-19T12:19:09.694+0000] {standard_task_runner.py:60} INFO - Started process 151 to run task
[2025-06-19T12:19:09.712+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T09:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmp38tsuh0p']
[2025-06-19T12:19:09.724+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask validate_data
[2025-06-19T12:19:09.902+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T09:00:00+00:00 [running]> on host b96384fab38e
[2025-06-19T12:19:10.090+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T09:00:00+00:00'
[2025-06-19T12:19:10.094+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T12:19:10.118+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T090000, start_date=20250619T121909, end_date=20250619T121910
[2025-06-19T12:19:10.181+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T12:19:10.215+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
