[2025-06-19T11:31:20.437+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T06:00:00+00:00 [queued]>
[2025-06-19T11:31:20.448+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T06:00:00+00:00 [queued]>
[2025-06-19T11:31:20.448+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T11:31:20.462+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 06:00:00+00:00
[2025-06-19T11:31:20.474+0000] {standard_task_runner.py:60} INFO - Started process 1070 to run task
[2025-06-19T11:31:20.481+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T06:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmppwos1jtx']
[2025-06-19T11:31:20.482+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask validate_data
[2025-06-19T11:31:20.549+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T06:00:00+00:00 [running]> on host 77bf71b7bc3a
[2025-06-19T11:31:20.662+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T06:00:00+00:00'
[2025-06-19T11:31:20.663+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T11:31:20.691+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T060000, start_date=20250619T113120, end_date=20250619T113120
[2025-06-19T11:31:20.740+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T11:31:20.764+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T12:06:16.414+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T06:00:00+00:00 [queued]>
[2025-06-19T12:06:16.453+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T06:00:00+00:00 [queued]>
[2025-06-19T12:06:16.455+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T12:06:16.573+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 06:00:00+00:00
[2025-06-19T12:06:16.600+0000] {standard_task_runner.py:60} INFO - Started process 1594 to run task
[2025-06-19T12:06:16.627+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T06:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmp7194d4o_']
[2025-06-19T12:06:16.629+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask validate_data
[2025-06-19T12:06:16.911+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T06:00:00+00:00 [running]> on host 77bf71b7bc3a
[2025-06-19T12:06:17.377+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T06:00:00+00:00'
[2025-06-19T12:06:17.386+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T12:06:17.429+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T060000, start_date=20250619T120616, end_date=20250619T120617
[2025-06-19T12:06:17.518+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T12:06:17.619+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T12:19:08.631+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T06:00:00+00:00 [queued]>
[2025-06-19T12:19:08.712+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T06:00:00+00:00 [queued]>
[2025-06-19T12:19:08.720+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T12:19:08.804+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 06:00:00+00:00
[2025-06-19T12:19:08.866+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T06:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmp0i_cer82']
[2025-06-19T12:19:08.874+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask validate_data
[2025-06-19T12:19:08.846+0000] {standard_task_runner.py:60} INFO - Started process 149 to run task
[2025-06-19T12:19:09.162+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T06:00:00+00:00 [running]> on host b96384fab38e
[2025-06-19T12:19:09.717+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T06:00:00+00:00'
[2025-06-19T12:19:09.720+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T12:19:09.748+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T060000, start_date=20250619T121908, end_date=20250619T121909
[2025-06-19T12:19:09.809+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T12:19:09.918+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
